FROM python:3.8

WORKDIR /usr/src/app

RUN curl https://raw.githubusercontent.com/kazulu/el-paraguas-bot/master/requirements.txt -o requirements.txt

RUN pip install --no-cache-dir -r requirements.txt