version: "3"

services:

  mongo:
    image: mongo:3.6
    restart: always

  app:
    build: ./docker/python
    working_dir: /usr/src/app
    restart: always
    volumes:
    - ./app:/usr/src/app
    links:
      - mongo
    command: ["python", "./main.py"]
