version: "3"

services:

  mongo:
    image: mongo:3.6
    restart: always
    volumes: 
      - ./docker/mongo/data:/data/db

  app:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    restart: always
    environment:
      TELEGRAM_TOKEN: "your token here"
    links:
      - mongo
    command: ["python", "./main.py"]
