version: "3"

services:

  mongo:
    image: mongo:3.6

  app:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
    links:
      - mongo
    command: ["python", "./main.py"]
