version: "3"

services:

  mongo:
    image: mongo:3.6
    restart: always
    volumes:
      - ./data:/data/db

  app:
    image: kazulu/el-paraguas-bot
    restart: always
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
    links:
      - mongo
    command: ["python", "./main.py"]
